<?php
namespace Client\Entities;

/**
 * This class was generated by the drest-client tool, and should be treated as a
 * plain data object
 *
 * ANY ALTERATIONS WILL BE OVERWRITTEN if the classes are regenerated
 * The variables declared are exposed by the rest endpoint provided when generating
 * these classes. However depending on the operation (GET/POST/PUT etc) used some
 * of these may not be populated / operational.
 */
class Address
{

    public $id = null;

    public $address = null;

    /**
     * @return Address $instance
     */
    public static function create()
    {
        return new self();
    }

    /**
     * @param string $id
     * @return Address $this
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string $address
     * @return Address $this
     */
    public function setAddress($address)
    {
        $this->address = $address;
        return $this;
    }


}
