<?php
namespace Client\Entities;

/**
 * This class was generated by the drest-client tool, and should be treated as a
 * plain data object
 *
 * ANY ALTERATIONS WILL BE OVERWRITTEN if the classes are regenerated
 * The variables declared are exposed by the rest endpoint provided when generating
 * these classes. However depending on the operation (GET/POST/PUT etc) used some
 * of these may not be populated / operational.
 */
class Profile
{

    public $id = null;

    public $title = null;

    public $firstname = null;

    public $lastname = null;

    /**
     * @var array $addresses
     */
    public $addresses = array();

    /**
     * @return Profile $instance
     */
    public static function create()
    {
        return new self();
    }

    /**
     * @param string $id
     * @return Profile $this
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @param string $title
     * @return Profile $this
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @param string $firstname
     * @return Profile $this
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
        return $this;
    }

    /**
     * @param string $lastname
     * @return Profile $this
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * @param Entities\Address $address
     * @return Profile $this
     */
    public function addAddress(Address $address)
    {
        $this->addresses[] = $address;
        return $this;
    }

    /**
     * @param array $addresses
     * @return Profile $this
     */
    public function addAddresses(array $addresses)
    {
        foreach ($addresses as $address) 
        {
            $this->addAddress($address);
        }
        return $this;
    }


}
